pipeline {
    agent any

    stages {
        stage ('Compile Stage') {

            steps {
                withMaven(maven : 'Maven-3.6.3') {
                    mvn clean compile
                }
            }
        }

        stage ('Testing Stage') {

            steps {
                withMaven(maven : 'Maven-3.6.3') {
                    mvn test
                }
            }
        }

    }
}