pipeline {
    agent any

    stages {
        stage ('Compile Stage') {

            steps {
                withMaven(maven : 'Maven-3.6.3') {
                	bat 'cd jenkins-example'
                    bat 'mvn clean compile'
                }
            }
        }

        stage ('Testing Stage') {

            steps {
                withMaven(maven : 'Maven-3.6.3') {
                	bat 'cd jenkins-example'
                    bat 'mvn test'
                }
            }
        }

    }
}